name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage:lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Build project
        run: npm run build

      - name: Check build artifacts
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.d.ts

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Necesario para el script de release
          token: ${{ secrets.GITHUB_TOKEN_PAT || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage:lcov

      - name: Build project
        run: npm run build

      - name: Check build artifacts
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.d.ts

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Check version status
        id: version-check
        run: |
          VERSION=$(node -p "require('./package.json').version")

          # Check if version exists in NPM
          if npm view nestjs-http-wrapper@$VERSION version > /dev/null 2>&1; then
            echo "npm_exists=true" >> $GITHUB_OUTPUT
            echo "Version $VERSION already exists in NPM"
          else
            echo "npm_exists=false" >> $GITHUB_OUTPUT
            echo "Version $VERSION is not in NPM"
          fi

          # Check if git tag exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "git_tag_exists=true" >> $GITHUB_OUTPUT
            echo "Git tag v$VERSION already exists"
          else
            echo "git_tag_exists=false" >> $GITHUB_OUTPUT
            echo "Git tag v$VERSION does not exist"
          fi

          # Determine if we should proceed with publishing
          if [ "$npm_exists" = "false" ]; then
            echo "should_publish=true" >> $GITHUB_OUTPUT
            echo "Will proceed with publishing (version not in NPM)"
          else
            echo "should_publish=false" >> $GITHUB_OUTPUT
            echo "Skipping publishing (version already in NPM)"
          fi

      - name: Create Git tag and push
        if: steps.version-check.outputs.should_publish == 'true' && steps.version-check.outputs.git_tag_exists == 'false'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"

      - name: Configure NPM
        if: steps.version-check.outputs.should_publish == 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          echo "NPM configuration completed"
          echo "Registry: $(npm config get registry)"
          echo "Auth token configured: $(npm config get //registry.npmjs.org/:_authToken | cut -c1-10)..."

      - name: Publish to NPM
        if: steps.version-check.outputs.should_publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.version-check.outputs.should_publish == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(node -p "require('./package.json').version")
          name: Release v$(node -p "require('./package.json').version")
          body: |
            ## Changes in this Release

            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.

            ## Installation

            ```bash
            npm install nestjs-http-wrapper@$(node -p "require('./package.json').version")
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
